version: '3'

volumes:
   database:
      driver: local

services:
   db:
      image: postgres:latest
      container_name: 'postgres-container'
      restart: always
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=postgres
      ports:
         - '5432:5432'
      volumes:
            - ./postgres-data:/var/lib/postgresql/data
      networks:
         - app_network

networks:
   app_network:
      external: true
