packages:
   - 'apps/*'
   - 'container/*'
   - 'content/*'
   - 'docker/*'
   - 'graphql/*'
   - 'home/*'
   - 'server/*'
   - 'services/*'
   - 'shared/*'
   - 'tools/*'
   - 'web'
   - 'bot'
dependencies:
   - tsconfig
