version: '3.7'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_root_password
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_password
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
