name: Maven Package

on:
  push:
      branches:
         - main # Adjust this to match the branch you want to trigger the workflow


jobs:
   build:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write

      steps:
         - uses: actions/checkout@v3
         - name: Set up JDK 11
           uses: actions/setup-java@v3
           with:
              java-version: '11'
              distribution: 'temurin'
              server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
              settings-path: ${{
                 github.workspace }} # location for the settings.xml file

         - name:
              Change directory to
              bot/muslim_bot
           run: cd bot/muslim_bot

         - name: Build with Maven
           run:
              mvn -B package --file
              pom.xml

         - name:
              Publish to GitHub Packages
              Apache Maven
           run:
              mvn deploy -s
              $GITHUB_WORKSPACE/settings.xml
           env:
              GITHUB_TOKEN:
                 ${{ github.token }}
