name: Publish sacred_texts to npmjs

on:
   push:
      branches:
         - main

jobs:
   build:
      name: Change to package directory
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Set up Node.js
           uses: actions/setup-node@v2
           with:
              node-version: '14.x'

         - name:
              Check Node.js and npm
              versions
           run: |
              node -v
              npm -v

         - name:
              Change to package
              directory
           run: cd packages/sacred_texts

         - name: Install dependencies
           run: npm ci

         - name: Publish to npm
           run: npm publish
           env:
              NODE_AUTH_TOKEN:
                 ${{ secrets.NODE_TOKEN
                 }}
