name: NPM Package packages/micu-ui

on:
   push:
      branches: ['main']
   pull_request:
      branches: ['main']

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-node@v3
           with:
              node-version: 16
         - name:
              Change to package
              directory
           working-directory: packages/ui
           run: |

              pnpm ci
              pnpm test

   publish-gpr:
      needs: build
      runs-on: ubuntu-latest
      permissions:
         packages: write
         contents: read
      steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-node@v3
           with:
              node-version: 16
              registry-url: https://npm.pkg.github.com/
         - name:
              Change to package
              directory
           working-directory: packages/ui
           run: |

              pnpm ci
              pnpm publish
           env:
              NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
